### ISSUE TITLE
5.2 Time Picker

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#160]
## User Story
As a user, I want to be able to set arrival and departure times for a polling station visit, including breaks, so that the duration of my visit can be accurately tracked.

## Description

The Observation page displays a card with information about the time spent at the current polling station. Tapping the card navigates the user to the Observation Time page, where they can set or adjust their arrival and departure times. 
Additionally, the 'Add Break in Observation' button allows the user to create a new break period, specifying the start and end times of their break.
 
## Preconditions

* User is logged into the app and navigates to a Polling Station Details page
* [**Alt. Flow 1**] The arrival time must be set.
* [**Alt. Flow 2**] The arrival and departure times are set, and several breaks have been added.

## Main Flow

1. User taps the "Arrival and departure time" card.
2. The system navigates to the "Observation time" page.
3. User selects the Arrival Time box, sets the time using the native picker, and confirms with "Ok."
4. User selects the Departure Time box, sets the time using the native picker, and confirms with "Ok."
5. User taps the 'Save observation time' button.
6. The system saves the arrival and departure times.

## Alt. Flow 1 (setting up breaks)

1. User taps the "Arrival and departure time" card.
2. The system navigates to the "Observation time" page.
3. User needs to set the arrival time.
4. User clicks the 'Add break in observation' button 
5. A new Break section appears.
6. The user sets the start and end times for the break and clicks the 'Save Observation Time' button.
7. The system saves the break details.

## Alt. Flow 2 (reset the entire page)

1. User taps the "Arrival and departure time" card.
2. User clicks the kebab menu
3. The system opens a bottom sheet displaying the "Clear Observation Time" option.
4. The user selects the "Clear Observation Time" option.
5. The system prompts user with a confirmation modal
6. The user confirms by selecting the 'Clear observation time' option
8. The system clears all the inputs on the page.

## Business Rules

1. The system must display native time pickers to enhance user experience.
2. The time can be edited at any time according to the user's preferences.
3. The "Add Break in Observation" button must be disabled/hidden until the arrival time has been completed.
4. The system must prevent users from setting a departure time before the arrival time or a start time before the end time.
5. The system must prevent adding breaks outside the arrival and departure times.
6. Once the breaks are saved, the system will automatically list the sections in ascending chronological order.

## Acceptance Criteria

1. [**Arrival and Departure Card**] The break counter should display the total number of breaks sections; ~~regardless of whether they are complete or empty~~. empty breaks will be discarded.
2. [**Arrival and Departure Card**] When only one time is set (arrival or departure), the other time will show "DD/MM/YYYY" and "HH" to indicate incomplete input.
4. When a new break is added, it will appear at the bottom of the page, and the view will automatically scroll to it.
5. The user can add multiple breaks between the arrival and departure times.
6. The breaks need to be sorted in ascending order by start time.
7. Each break section should include a delete icon, enabling users to remove the break as needed.
8. ~~Each time picker must include a reset button that allows the user to reset the specific input~~ The date input will display an `x` icon that will allow resetting the date to the initial state. No reset button will be present on the actual time picker.
9. Selecting and confirming the 'Clear Observation Time' option should automatically clear the inputs and save the changes.
10. When using the 'Back' function or button, the user will be prompted with an information modal if there are unsaved changes, offering 'Discard' and 'Save Changes' options.
11. An error message should be shown in a modal if the breaks fall outside the arrival and departure times, or if the departure time is set before the end of the last break.

## Additional Information (optional)

* Note: the ACs marked with (**?**) are pending approval.
* **Figma references**: 
     a) Arrival and departure time card: empty, partial defined and defined states [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6705-33433&t=3FoPF9H5LULbDNzM-4)
    b) Observation Time page: [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6705-33007&t=aXpbrTAYxheAb1SH-4) 
    c) Confirmation Modal: [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6850-18388&t=3FoPF9H5LULbDNzM-4) 
    d) Information Modal: [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6850-18212&t=3FoPF9H5LULbDNzM-4) 
    e) Error Modal: [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6771-4417&t=3FoPF9H5LULbDNzM-4) 

## Tasks
- [x] new card to display arrival/departure time information
- [x] new page for observation time
- [x] new break section with start/end time and delete option
- [x] clear observation time options sheet and confirmation modal
- [x] save changes confirmation modal
- [x] logic and modal for inability to save observation time (observation time is before the end of the last break; arrival time is after the start of the first break; break out of arrival/departure time interval)
- [x] error on departure time input for trying to set departure time before arrival time

**Comment by andrei-manda** [comment]
This feature has been enhanced, and I will comment with the previous version so we can keep track of the changes:

## User Story
As a user, I want to be able to set arrival and departure times for a polling station so that my visit duration can be tracked.

## Description

Once a user adds a polling station, the details page will display a section containing two selectors: 
    - one for selecting the arrival date and time
    - one for selecting the departure date and time  
 
## Preconditions

* User is logged into the app and is on the Polling Station details page.

## Main Flow

1. User selects the Arrival Time box
2. The system presents the OS native picker
3. User sets their arrival time accordingly and clicks on the "Ok" button
4. Changes are saved
5. User selects the Departure Time box.
6. The system presents the OS native picker
7. User sets their departure time accordingly and clicks on the "Ok" button.
8. Changes are saved


## Business Rules

1. The system must display native pickers for both arrival and departure times to enhance user experience.
2. The time can be edited at any time according to the user's preferences.
3. The system must not allow users to set a departure time prior to the arrival time.

## Additional Information (optional)

* Figma references [here](https://www.figma.com/file/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?type=design&node-id=1150-3033&mode=design&t=FfPddr8DRbWW6wof-4)
