### ISSUE TITLE
Media Files & Notes Enhancements

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#615]
## Tasks List

- [ ] Remove the crop option when taking a photo
- [ ] Enable adding multiple files at once when opening the gallery
- [ ] Update the 'Add Note' modal to save the note upon the first click of the 'Save' button
- [ ] Implement a preview feature for uploaded media files
